url: https://beingtechnicalwriter.com/apidocumentation/
plugins:
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-seo

destination: _site
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

repository: gautriv/apidocumentation

output: web

site_title: API Documentation - A step by step guide for technical writers


github_editme_path: gautriv/apidocumentation/blob/gh-pages/

google_analytics: UA-170189185-1
google_analytics4: G-8VQGBYV0J

exclude:
  - .gitignore
  - vendor

collections:
  tooltips:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
      sidebar: home_sidebar
      topnav: topnav
      
sidebars:
- sidebar


####### jekyll seo tag configuration #######
title: API Documentation
tagline: A step by step guide for technical writers
description: A course for technical writers looking to learn each and every aspect of API documentation.

url: https://beingtechnicalwriter.com/apidocumentation/
social:
  name: Gaurav Trivedi
  links:
    - https://www.linkedin.com/in/gauravtrivedi1988/
    - https://github.com/gautriv/

lang: en_US

